# This file is augmented with more nav pages by drush mk:docs command.
site_name: Polymer Drupal
site_author: "Les Peabody"
site_description: A tool for facilitating WebOps workflows.
site_dir: docs_site
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
repo_url: https://github.com/digitalpolygon/polymer-drupal
repo_name: digitalpolygon/polymer-drupal
plugins:
  - search
  - git-revision-date-localized
markdown_extensions:
  - toc:
      permalink: true
  - admonition: {}
  - meta: {}
  - pymdownx.magiclink: {}
  - pymdownx.keys: {}
  - pymdownx.snippets: {}
  - pymdownx.highlight:
      use_pygments: true
      # https://github.com/squidfunk/mkdocs-material/issues/506#issuecomment-338007823
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.inlinehilite: {}
  - pymdownx.superfences: {}
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - Home: index.md
  - Development: development.md
  - Commands:
      - drupal:
          - "drupal:multisite:update-all": commands/drupal_multisite_update_all.md
          - "drupal:update": commands/drupal_update.md
          - "drupal:config:import": commands/drupal_config_import.md
          - "drupal:deploy:hook": commands/drupal_deploy_hook.md
          - "drupal:multisite:update-all": commands/drupal_multisite_update_all.md
          - "drupal:multisite:create": commands/drupal_multisite_create.md
          - "drupal:site:install": commands/drupal_site_install.md
          - "drupal:init:settings": commands/drupal_init_settings.md
          - "drupal:site:sync:all-sites": commands/drupal_site_sync_all_sites.md
          - "drupal:site:sync": commands/drupal_site_sync.md
          - "drupal:site:sync:db:all-sites": commands/drupal_site_sync_db_all_sites.md
          - "drupal:site:sync:database": commands/drupal_site_sync_database.md
          - "drupal:site:sync:files": commands/drupal_site_sync_files.md
          - "drupal:site:sync:private-files": commands/drupal_site_sync_private_files.md
