<?php

use DigitalPolygon\Polymer\Environment\EnvironmentDetectorBase;
use DigitalPolygon\Polymer\Environment\AcquiaEnvironmentDetector;
use DigitalPolygon\Polymer\Environment\PantheonEnvironmentDetector;

/**
 * @file
 * Generated by Polymer.
 */

/**
 * Site path.
 *
 * @var string $site_path
 * This is always set and exposed by the Drupal Kernel.
 */
$site_name = str_replace('sites/', '', $site_path);

/**
 * Site path.
 *
 * @var string $repo_root
 *  Path to the repository root (assumed to be parent of DRUPAL_ROOT).
 */
if (!isset($repo_root)) {
    $repo_root = realpath(DRUPAL_ROOT . '/..');
}

$settings_files = [];

// Default global settings.
// @todo Add polymer specific settings file as needed.
$polymer_settings_files = ['config'];
if ($polymer_settings_files) {
    foreach ($polymer_settings_files as $polymer_settings_file) {
        $settings_files[] = __DIR__ . "/$polymer_settings_file.settings.php";
    }
}

// Custom global and site-specific settings.
$settings_files[] = DRUPAL_ROOT . '/sites/settings/global.settings.php';
$settings_files[] = DRUPAL_ROOT . "/sites/$site_name/settings/includes.settings.php";

if (EnvironmentDetectorBase::isCiEnv()) {
    // Custom global and site-specific CI settings.
    $settings_files[] = DRUPAL_ROOT . "/sites/settings/ci.settings.php";
    $settings_files[] = DRUPAL_ROOT . "/sites/$site_name/settings/ci.settings.php";
}

// Local global and site-specific settings.
if (AcquiaEnvironmentDetector::isLocalEnv() || PantheonEnvironmentDetector::isLocalEnv()) {
    // Use settings.local.php because that's what Drupal scaffold uses.
    $settings_files[] = DRUPAL_ROOT . '/sites/settings/settings.local.php';
    $settings_files[] = DRUPAL_ROOT . "/sites/$site_name/settings.local.php";
}

foreach ($settings_files as $settings_file) {
    if (file_exists($settings_file)) {
      // phpcs:ignore
      require $settings_file;
    }
}
