<?php

namespace DigitalPolygon\PolymerDrupalTest\phpunit\unit;

use DigitalPolygon\Polymer\Drupal\Contracts\Event\AlterSettingsFilesEvent;
use DigitalPolygon\Polymer\Drupal\Contracts\Event\CollectSettingsFilesEvent;
use DigitalPolygon\Polymer\Drupal\Contracts\Event\DrupalSettingsEvents;
use DigitalPolygon\Polymer\polymer_drupal\Plugin\Commands\SetupCommands;
use League\Container\Container;
use PHPUnit\Framework\TestCase;
use Robo\Config\Config;
use Symfony\Component\EventDispatcher\EventDispatcher;

/**
 * Exposes the protected settings-file generation step.
 */
class InspectableSetupCommands extends SetupCommands
{
    public function generate(string $site): void
    {
        $this->createDynamicSiteSettingsFile($site);
    }
}

/**
 * Covers polymer-drupal's side of the settings event contract: the emitter
 * dispatches collect then alter and writes the surviving snippets to the
 * site's polymer-extensions.settings.php.
 */
class SettingsFileGenerationTest extends TestCase
{
    private string $docroot;

    protected function setUp(): void
    {
        $this->docroot = sys_get_temp_dir() . '/polymer-settings-test-' . bin2hex(random_bytes(4));
        mkdir($this->docroot . '/sites/default/settings', 0777, true);
    }

    protected function tearDown(): void
    {
        $settingsFile = $this->settingsPath();
        if (file_exists($settingsFile)) {
            unlink($settingsFile);
        }
        rmdir($this->docroot . '/sites/default/settings');
        rmdir($this->docroot . '/sites/default');
        rmdir($this->docroot . '/sites');
        rmdir($this->docroot);
    }

    private function settingsPath(): string
    {
        return $this->docroot . '/sites/default/settings/polymer-extensions.settings.php';
    }

    private function commands(EventDispatcher $dispatcher): InspectableSetupCommands
    {
        $container = new Container();
        $container->add('eventDispatcher', $dispatcher);
        $container->add(CollectSettingsFilesEvent::class, new CollectSettingsFilesEvent());
        $container->add(AlterSettingsFilesEvent::class, new AlterSettingsFilesEvent());

        $commands = new InspectableSetupCommands();
        $commands->setContainer($container);
        $commands->setConfig(new Config(['docroot' => $this->docroot]));

        return $commands;
    }

    public function testCollectedSnippetsAreWrittenInOrderWithHeader(): void
    {
        $dispatcher = new EventDispatcher();
        $dispatcher->addListener(
            DrupalSettingsEvents::COLLECT_SETTINGS_FILES,
            static function (CollectSettingsFilesEvent $event): void {
                $event->addSettingsFile('first', '// first snippet');
                $event->addSettingsFile('second', '// second snippet');
            }
        );

        $this->commands($dispatcher)->generate('default');

        $content = (string) file_get_contents($this->settingsPath());
        $this->assertStringStartsWith("<?php\n", $content);
        $this->assertStringContainsString('This file is generated by polymer-drupal.', $content);
        $this->assertStringContainsString('// first snippet', $content);
        $this->assertStringContainsString('// second snippet', $content);
        $this->assertLessThan(
            strpos($content, '// second snippet'),
            strpos($content, '// first snippet'),
            'Snippets must be written in contribution order.'
        );
    }

    public function testAlterListenerCanDropACollectedSnippet(): void
    {
        $dispatcher = new EventDispatcher();
        $dispatcher->addListener(
            DrupalSettingsEvents::COLLECT_SETTINGS_FILES,
            static function (CollectSettingsFilesEvent $event): void {
                $event->addSettingsFile('keep', '// keep me');
                $event->addSettingsFile('drop', '// drop me');
            }
        );
        $dispatcher->addListener(
            DrupalSettingsEvents::ALTER_SETTINGS_FILES,
            static function (AlterSettingsFilesEvent $event): void {
                $files = $event->getSettingsFiles();
                unset($files['drop']);
                $event->setSettingsFiles($files);
            }
        );

        $this->commands($dispatcher)->generate('default');

        $content = (string) file_get_contents($this->settingsPath());
        $this->assertStringContainsString('// keep me', $content);
        $this->assertStringNotContainsString('// drop me', $content);
    }

    public function testListenersReceiveTheTargetSite(): void
    {
        $dispatcher = new EventDispatcher();
        $collectSite = null;
        $alterSite = null;
        $dispatcher->addListener(
            DrupalSettingsEvents::COLLECT_SETTINGS_FILES,
            static function (CollectSettingsFilesEvent $event) use (&$collectSite): void {
                $collectSite = $event->getSite();
            }
        );
        $dispatcher->addListener(
            DrupalSettingsEvents::ALTER_SETTINGS_FILES,
            static function (AlterSettingsFilesEvent $event) use (&$alterSite): void {
                $alterSite = $event->getSite();
            }
        );

        $this->commands($dispatcher)->generate('default');

        $this->assertSame('default', $collectSite);
        $this->assertSame('default', $alterSite);
    }

    public function testNoContributionsStillWritesTheHeaderFile(): void
    {
        $this->commands(new EventDispatcher())->generate('default');

        $this->assertFileExists($this->settingsPath());
        $content = (string) file_get_contents($this->settingsPath());
        $this->assertStringContainsString('This file is generated by polymer-drupal.', $content);
    }
}
