project:
  recipe: common
  profile:
    name: minimal

docroot: ${repo.root}/web

cm:
  # Possible values: core-only, config-split, none.
  strategy: config-split
  core:
    # The parent directory for configuration directories, relative to the docroot.
    path: ../config
    dirs:
      # Corresponding value is defined in config.settings.php.
      sync:
        path: ${cm.core.path}/default
    # Install site directly from existing config.
    # This cannot be used if your install profile implements hook_install.
    install_from_config: false

sync:
  # By default, files are not synced during sync:refresh.
  # Set this value to 'true' or pass -D sync.public-files=true
  # to override this behavior.
  public-files: false
  private-files: false
  # Paths to exclude during file syncing operations.
  exclude-paths:
    - styles
    - css
    - js
  commands:
    - drupal:site:sync:database
    - drupal:site:sync:files
    - drupal:site:sync:private-files
    # To make sure that the states between local and remote are as close to identical as possible before running an update operation.
    # That's why files needs to be synchronized locally first.
    # Command order can be changed as per the need in custom polymer.config file.
    - drupal:update
